name: XLPrint
favicon: null
layout_spectrum: 0.64653
typography_spectrum: 0.88803
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#01538d'
    - '#7da6c3'
    - '#bcd2e1'
    - '#3572a2'
  brandStrength: 0.7592874024994671
  lightness: 0.48691536975093186
  saturation: 0.4808377062436193
  rhythmicContrast: 0.43300785357132554
purpose: []
